### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by addaleax** [tradity/tradity-bus#1]
There is almost no explicit documentation here… but there should be.

**Comment by addaleax** [comment]
Closing in favour of deprecating this module completely.

**Comment by tbakhai** [comment]
Yes! :clap:

**Comment by addaleax** [comment]
@BonsaiOfHappiness ?

**Comment by tbakhai** [comment]
Did I misunderstand? Is this not a thing to celebrate? :D

**Comment by addaleax** [comment]
Um, well… it’s more or less sending a huge chunk of code to the graveyard… so, it’s a very… “neutral” thing, I guess? :D

**Comment by tbakhai** [comment]
Oh - then I misunderstood partly :D... Farewell then
